QuarterlySales/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuarterlySales.Models;
using QuarterlySales.Models.Validation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuarterlySales.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EmployeeController : Controller
    {
        private IRepository<Employee> data { get; set; }
        public EmployeeController(IRepository<Employee> rep) => data = rep;

        public IActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public ViewResult Add()
        {
            ViewBag.Employees = data.List(new QueryOptions<Employee> { OrderBy = e => e.FirstName });
            return View();
        }

        [HttpPost]
        public IActionResult Add(Employee employee)
        {
            string message = Validate.CheckEmployee((Repository<Employee>)data, employee);
            string message2 = CheckManagerHireDate(employee);
            if (!string.IsNullOrEmpty(message))
            {
                ModelState.AddModelError(nameof(Employee.DateOfBirth), message);
            }

            message = Validate.CheckManagerEmployeeMatch((Repository<Employee>)data, employee);
            if (!string.IsNullOrEmpty(message))
            {
                ModelState.AddModelError(nameof(Employee.ManagerId), message);
            }

            if (!string.IsNullOrEmpty(message2))
            {
                ModelState.AddModelError(nameof(Employee.ManagerId), message2);
            }

            if (ModelState.IsValid)
            {
                data.Insert(employee);
                data.Save();
                TempData["message"] = $"Employee {employee.FullName} added";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Employees = data.List(new QueryOptions<Employee> { OrderBy = e => e.FirstName });
                return View();
            }
        }
        private string CheckManagerHireDate(Employee employee)
        {
            Employee manager = data.Get(employee.ManagerId);
            
            if (employee.DateOfHire < manager.DateOfHire)
            {
                return "Manager must be hired before new employee";
            }
            else
            {
                return string.Empty;
            }
        }
    }
}

QuarterlySales/Controllers/SalesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuarterlySales.Models;
using QuarterlySales.Models.Validation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuarterlySales.Controllers
{
    [Authorize]
    public class SalesController : Controller
    {
        private IQuarterlySalesUnitOfWork data { get; set; }
        public SalesController(IQuarterlySalesUnitOfWork unit) => data = unit;

        public IActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public ViewResult Add()
        {
            ViewBag.Employees = data.Employees.List(new QueryOptions<Employee> { OrderBy = e => e.FirstName });
            return View();
        }

        [HttpPost]
        public IActionResult Add(Sales sales)
        {
            string message = Validate.CheckSales(data, sales);
            string message2 = CheckSalesYearAndQuarter(sales);
            if (!string.IsNullOrEmpty(message))
            {
                ModelState.AddModelError(nameof(sales.EmployeeId), message);
            }
            
            if (!string.IsNullOrEmpty(message2))
            {
                ModelState.AddModelError(nameof(sales.Quarter), message2);
            }

            if (ModelState.IsValid)
            {
                data.Sales.Insert(sales);
                data.Save();
                TempData["message"] = $"Sales added";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Employees = data.Employees.List(new QueryOptions<Employee> { OrderBy = e => e.FirstName });
                return View();
            }
        }

        private string CheckSalesYearAndQuarter(Sales sale)
        {
            int hireQuarter = 0;
            Employee employee = data.Employees.Get(sale.EmployeeId);

            int hireYear = employee.DateOfHire.Value.Year;
            int hireMonth = employee.DateOfHire.Value.Month;
            switch (hireMonth)
            {
                case 1:
                case 2:
                case 3:
                    hireQuarter = 1;
                    break;
                case 4:
                case 5:
                case 6:
                    hireQuarter = 2;
                    break;
                case 7:
                case 8:
                case 9:
                    hireQuarter = 3;
                    break;
                case 10:
                case 11:
                case 12:
                    hireQuarter = 4;
                    break;
                default:
                    break;
            }

            if(sale.Year < hireYear)
            {
                return $"Sale year and quarter must be the hire date of {hireYear} Q{hireQuarter} or later.";
            }
            else if (sale.Year == hireYear && sale.Quarter < hireQuarter)
            {
                return $"Sale year and quarter must be the hire date of {hireYear} Q{hireQuarter} or later.";
            }
            else
            {
                return string.Empty;
            }
        }
    }
}

QuarterlySales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item col">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index" asp-route-id="">Home</a>
                        </li>

                        <partial name="_NavBar" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <temp-message />
            @RenderBody()
        </main>
    </div>
</body>
</html>

QuarterlySales/Views/Shared/_NavBar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> signInManager
@if (signInManager.IsSignedIn(User))
{
    // signed-in user - logout button, username and welcome message
    <li class="nav-item col">
        <a class="nav-link text-dark" asp-controller="Sales" asp-action="Add">Add Sales</a>
    </li>
    @if (User.IsInRole("Admin"))
    {
        <li class="nav-item col">
            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Add">Add Employee</a>

        </li>
    }
    <li class="nav-item col">
        <span class="text-dark">Welcome, @User.Identity.Name</span>
    </li>
    @if (User.IsInRole("Admin"))
    {
        <li class="nav-item col">
            <a asp-action="Index" asp-controller="User" class="nav-link text-dark">Manage Users</a>
        </li>
    }
    <li class="nav-item col">
        <form method="post" asp-action="Logout" asp-controller="Account" asp-area="">
            <input type="submit" value="Log Out" />
        </form>
    </li>
}
else
{
    // get current action
    var action = ViewContext.RouteData.Values["action"]?.ToString();

    // anonymous user - register link and login button
    <li class="nav-item col @Nav.Active("Register", action)">
        <a asp-action="Register" asp-controller="Account" class="nav-link text-dark">Register</a>
    </li>
    <li class="nav-item col">
        <a asp-action="Login" asp-controller="Account" class="nav-link text-dark">Log In</a>
    </li>
}

QuarterlySales/Views/Shared/_PagingLinksPartial.cshtml
@{
    for (int x = 1; x <= Model.TotalPages; x++)
    {
        <paging-link number="@x" current="@Model.CurrentRoute"></paging-link>
    }
}